### ISSUE TITLE
Is this converted from the official EBNF?

### ISSUE THREAD

**Issue by DanielYWoo** [rcatalan/antlr-saphana#1]
A very interesting project, may I ask you how do you generate this g4? I cannot find the official g4 or EBNF of Hana 1.x or 2.x.
BTW, it seems create_table is missing.

**Comment by rcatalan** [comment]
Hi Daniel, thank you for your interest.
I created this project as part of my master degree's thesis. The goal of my project was to generate unit tests on stored procedures, that's why the grammar is not complete.
I created the g4, manually, according to the SAP/HANA documentation
